---
dist: focal
matrix:
  fast_finish: true
  include:
    - os: linux
      language: python
      python: "3.9"
      addons:
        snaps:
          - name: lxd
            channel: stable
git:
  clone: false
install:
  - git clone https://github.com/$TRAVIS_REPO_SLUG.git nvim
  - cd nvim
  - sudo /snap/bin/lxd waitready
  - sudo /snap/bin/lxd init --auto
  - sudo chgrp travis /var/snap/lxd/common/lxd/unix.socket
  - pip3 install -U pip
  - pip3 install -r requirements.txt
script:
  - python --version
  - molecule --version
  - ansible --version
  - ansible-lint --version
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
