---
- name: 02-install-neovim | Install neovim build requirements
  ansible.builtin.package:
    name: "{{ nvim_build_requirements }}"
  become: true

- name: 02-install-neovim | Set neovim source destination
  ansible.builtin.set_fact:
    neovim_src_dest: "{{ nvim_src_dest | default(ansible_env.HOME + '/src/neovim') }}"

- name: 02-install-neovim | Clone neovim source
  ansible.builtin.git:
    repo: https://github.com/neovim/neovim.git
    dest: "{{ neovim_src_dest }}"
    version: master
    depth: 1

- name: 02-install-neovim | Register nvim_exists
  ansible.builtin.stat:
    path: /usr/local/bin/nvim
  register: nvim_check

- name: 02-install-neovim | Build Neovim
  community.general.make:
    chdir: "{{ neovim_src_dest }}"
    params: CMAKE_BUILD_TYPE=RelWithDebInfo
  when: not nvim_check.stat.exists

- name: 02-install-neovim | Install Neovim
  community.general.make:
    chdir: "{{ neovim_src_dest }}"
    target: install
  become: true
  when: not nvim_check.stat.exists
