---
# tasks file for ansible-pyenv
- name: Set distro-specific variables
  ansible.builtin.include_vars: '{{ item }}'
  with_first_found:
    - '{{ ansible_os_family }}.yml'
    - default.yml

# tasks file for ansible-nvim
- name: Define role facts
  ansible.builtin.import_task: "01-define-role-facts.yml"

- name: Build and install neovim
  ansible.builtin.import_task: "02-install-neovim.yml"

- name: Install neovim providers
  ansible.builtin.import_task: "03-install-neovim-helpers.yml"

- name: Install nvim config and prerequistes
  ansible.builtin.import_task: "04-install-neovim-rc.yml"
