---
# handlers file for ansible-nvim
- name: restart snapd service
  ansible.builtin.systemd:
    name: snapd
    state: restarted
    enabled: true

- name: restart apparmor service
  ansible.builtin.systemd:
    name: apparmor
    state: restarted
    enabled: true

- name: restart snapd.apparmor service
  ansible.builtin.systemd:
    name: snapd.apparmor
    state: restarted
    enabled: true
  when: ansible_os_family == "Archlinux"
