---
- name: Converge
  hosts: all
  vars:
    nvim_user: shadowwalker
    fnm_install_npmrc: true
    fnm_npmrc_suffix: ".config/npm/config"
  tasks:
    - name: Add shadowwalker user
      ansible.builtin.user:
        name: "{{ nvim_user }}"
        create_home: true
        shell: /bin/bash

    - name: Run nvim role
      ansible.builtin.include_role:
        name: ansible-role-nvim
