---
- name: Prepare
  hosts: all
  become: true
  gather_facts: false

  roles:
    - role: buluma.bootstrap
    - role: buluma.git
    - role: hurricanehrndz.pyenv
    # - role: hurricanehrndz.fnm
    - role: hurricanehrndz.rustup
