---
- name: Verify
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Get nvim information
      ansible.builtin.shell: nvim -v
      register: nvim_version

    - name: Print return information from the previous task
      ansible.builtin.debug:
        msg: nvim_version
        verbosity: 2
