---
- name: Verify
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Verify nvim exists
      ansible.builtin.command: nvim -h
      register: result
      changed_when: result is not succeeded

    - name: Debug nvim result
      ansible.builtin.debug:
        var: result
        verbosity: 2
