---
- name: Verify
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Get Nvim version
      command: nvim -v
      register: nvim_version

    - name: Debug
      ansible.builtin.debug:
        var: nvim_version
        verbosity: 2
