---
- name: Converge
  hosts: all
  vars:
    nvim_user: hurricanehrndz
    fnm_install_npmrc: true
    fnm_npmrc_suffix: ".config/npm/config"
  tasks:
    - name: Add hurricanehrndz user
      user:
        name: "{{ nvim_user }}"
        create_home: yes
        shell: /bin/bash

    - name: Run nvim role
      include_role:
        name: nvim
